ERROR: 2020/09/28 12:45:51 main.go:427: Error connecting to node for sync: dial tcp [::1]:1235: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:45:54 main.go:427: Error connecting to node for sync: dial tcp [::1]:1236: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:45:56 main.go:427: Error connecting to node for sync: dial tcp [::1]:1237: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:45:58 main.go:427: Error connecting to node for sync: dial tcp [::1]:1238: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:46:00 main.go:427: Error connecting to node for sync: dial tcp [::1]:1239: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:50:02 main.go:427: Error connecting to node for sync: dial tcp [::1]:1235: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:50:04 main.go:427: Error connecting to node for sync: dial tcp [::1]:1236: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:50:07 main.go:427: Error connecting to node for sync: dial tcp [::1]:1237: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:50:09 main.go:427: Error connecting to node for sync: dial tcp [::1]:1238: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:50:11 main.go:427: Error connecting to node for sync: dial tcp [::1]:1239: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:54:45 main.go:427: Error connecting to node for sync: dial tcp [::1]:1235: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:54:47 main.go:427: Error connecting to node for sync: dial tcp [::1]:1236: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:54:49 main.go:427: Error connecting to node for sync: dial tcp [::1]:1237: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:54:52 main.go:427: Error connecting to node for sync: dial tcp [::1]:1238: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:54:54 main.go:427: Error connecting to node for sync: dial tcp [::1]:1239: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:56:01 main.go:427: Error connecting to node for sync: dial tcp [::1]:1235: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:56:03 main.go:427: Error connecting to node for sync: dial tcp [::1]:1236: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:56:06 main.go:427: Error connecting to node for sync: dial tcp [::1]:1237: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:56:08 main.go:427: Error connecting to node for sync: dial tcp [::1]:1238: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 12:56:10 main.go:427: Error connecting to node for sync: dial tcp [::1]:1239: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 15:14:41 main.go:428: Error connecting to node for sync: dial tcp [::1]:1235: bind: An operation on a socket could not be performed because the system lacked sufficient buffer space or because a queue was full.
ERROR: 2020/09/28 15:22:13 main.go:428: Error sending data to node {localhost:9091 localhost:1235}: rpc: can't find method Store.AppendEntry
ERROR: 2020/09/28 15:25:00 main.go:428: Error sending data to node {localhost:9092 localhost:1236}: rpc: can't find method Store.AppendEntry
ERROR: 2020/09/28 15:39:37 main.go:428: Error sending data to node {localhost:9091 localhost:1235}: rpc: can't find method Store.AppendEntry
ERROR: 2020/09/28 15:51:15 main.go:430: Error sending data to node {localhost:9091 localhost:1235}: rpc: can't find method Store.AppendEntry
ERROR: 2020/09/28 15:54:58 main.go:430: Error sending data to node {localhost:9091 localhost:1235}: rpc: can't find method Store.AppendEntry
ERROR: 2020/09/28 16:01:32 main.go:430: Error sending data to node {localhost:9091 localhost:1235}: reading body gob: decoding into local type *int, received remote type uint
ERROR: 2020/09/28 16:05:01 main.go:430: Error connecting to node for sync: dial tcp [::1]:1236: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:05:11 main.go:430: Error connecting to node for sync: dial tcp [::1]:1237: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:05:25 main.go:430: Error connecting to node for sync: dial tcp [::1]:1238: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:05:37 main.go:430: Error connecting to node for sync: dial tcp [::1]:1239: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:06:28 main.go:430: Error connecting to node for sync: dial tcp [::1]:1236: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:10:11 main.go:430: Error connecting to node for sync: dial tcp [::1]:1236: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:10:20 main.go:430: Error connecting to node for sync: dial tcp [::1]:1237: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:10:22 main.go:430: Error connecting to node for sync: dial tcp [::1]:1238: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:10:24 main.go:430: Error connecting to node for sync: dial tcp [::1]:1239: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:12:37 main.go:430: Error connecting to node for sync: dial tcp [::1]:1236: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:12:39 main.go:430: Error connecting to node for sync: dial tcp [::1]:1237: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:12:41 main.go:430: Error connecting to node for sync: dial tcp [::1]:1238: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 16:12:44 main.go:430: Error connecting to node for sync: dial tcp [::1]:1239: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 14:55:16 main.go:430: Error connecting to node for sync: dial tcp [::1]:1236: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 14:55:17 main.go:430: Error connecting to node for sync: dial tcp [::1]:1237: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 14:55:18 main.go:430: Error connecting to node for sync: dial tcp [::1]:1238: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2020/09/28 14:55:20 main.go:430: Error connecting to node for sync: dial tcp [::1]:1239: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2021/08/29 17:57:22 main.go:430: Error connecting to node for sync: dial tcp [::1]:1235: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2021/08/29 17:57:25 main.go:430: Error connecting to node for sync: dial tcp [::1]:1236: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2021/08/29 17:57:27 main.go:430: Error connecting to node for sync: dial tcp [::1]:1237: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2021/08/29 17:57:29 main.go:430: Error connecting to node for sync: dial tcp [::1]:1238: connectex: No connection could be made because the target machine actively refused it.
ERROR: 2021/08/29 17:57:32 main.go:430: Error connecting to node for sync: dial tcp [::1]:1239: connectex: No connection could be made because the target machine actively refused it.
